plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tmkplant.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.tmkplant.app"
        minSdk 21
        targetSdk 34
        versionCode 59
        versionName "1.58"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
